export const UPDATE_POSTS = "UPDATE_POSTS";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT = "LOGOUT";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
